USE  basicset;

CREATE TABLE festivamood(1id int,2festival_name varchar(30),3DATE date,4day varchar(30),5Special_for varchar(30),6state varchar(30),7food varchar(30),8gender_special varchar(30),9worship_god varchar(30),10wear_new_dress varchar(30),11festive_days int,12seasion varchar(30),13Amavase varchar(30),14Hunnime varchar(30),15religion varchar(30),16fair_place varchar(30),17place_god varchar(30),18celebrating_members int,19were_iAm_Locate varchar(30),country varchar(30)); 
INSERT INTO festivamood VALUES(1,'Sankrati','2023-01-15','sunday','Ellu_bella','KA,AP,KL','Vabbottu','Both','ALL','May be',2,'winter','no','no','Hindu','Shabari male','Ayappa',10,'Banglore','india');
INSERT INTO festivamood VALUES(2,'Shivaratri','2023-02-12','monday','pooje','all over world','upavasa','Both','Shiva','no',1,'winter','yes','no','Hindu','Aurad','Amareshwar',15,'Banglore','india');
INSERT INTO festivamood VALUES(3,'Holi ','2023-03-04','tuesday','banna','KA,AP,MH','Holige','Both','Kamanna','No',1,'winter','no','no','Hindu','kalburgi','sharanabasappa',30,'Banglore','india');
INSERT INTO festivamood VALUES(4,'Ugadi','2023-03-22','Monday','hosavarusha for hindu','all over world','Holige ','Both','ALL','yes',1,'summmer','yes','no','Hindu','Kadaganchi','gramadevate',6,'Banglore','india');
INSERT INTO festivamood VALUES(5,'Sri Ram navami','2023-03-30','wednesday','ram birth','all over world','panaka','Both','ALL','yes',1,'summer','no','yes','Hindu','Ayoddhya','ram',100,'Banglore','india');
INSERT INTO festivamood VALUES(6,'Hanuman  jayanti','2023-04-06','wednesday','hanuma birth','all over world','panaka','Both','ALL','yes',1,'summer','yes','no','Hindu','hanuman palces','hanuma',10,'Banglore','india');
INSERT INTO festivamood VALUES(7,'Akshya tratiya','2023-04-22','saturday','basava jayanti','all over india','holige_mavin rasa','Both','ALL','yes',1,'summer','no','no','Hindu','basavakalyan','basavanna',10,'Banglore','india');
INSERT INTO festivamood VALUES(8,'Ramjan','2023-04-22','saturday','---','all over world','------','Both','ALL','yes',30,'summer','yes','yes','muslim','------','------',10,'Banglore','india');
INSERT INTO festivamood VALUES(9,'GURU-Purnime','2023-06-03','monday','Guru pooje','all over india','sweets','Both','ALL','May be',1,'rainy','no','yes','Hindu','-----','-----',10,'Banglore','india');
INSERT INTO festivamood VALUES(10,'moharam','2023-06-29','saturday','peer','KA','malodi','Both','ALL','yes',15,'rainy','',-'-','all','places ','--',10,'Banglore','india');
INSERT INTO festivamood VALUES(11,'shravan','2023-08-16','tuesday','prayer','KA,MH','sweets','Both','ALL','May be',30,'winter','no','no','Hindu','--- ','-----',10,'Banglore','india');
INSERT INTO festivamood VALUES(12,'ganesh charthi','2022-09-15','monday','ganapathi','india','holige','Both','ALL','May be',5,'rainy','no','no','Hindu','------','------',10,'Banglore','india');
INSERT INTO festivamood VALUES(13,'dasara','2022-01-15','saturday','devi','india','ckwvg','Both','ALL','May be',2,'winter','no','no','Hindu','devaru','shiva',10,'Banglore','india');
INSERT INTO festivamood VALUES(14,'dipavali','2022-01-15','tuesday','lakshmi','india','sdvhs','Both','ALL','May be',2,'winter','no','no','Hindu','shiva','devaru',10,'Banglore','india');
INSERT INTO festivamood VALUES(15,'srikrishna janmastami','2022-01-15','wednesday','krishana','KA','jfag','Both','ALL','May be',2,'winter','no','no','hindu','devi','devi',10,'Banglore','india');
INSERT INTO festivamood VALUES(16,'gouri pooje','2022-01-15','sunday','gouri','india','chitranna','Both','ALL','May be',2,'winter','no','no','Hindu','lakshmi','lakshmi',10,'Banglore','india');
INSERT INTO festivamood VALUES(17,'ayudha pooje','2022-01-15','saturday','dasara','india','sweet','Both','ALL','May be',2,'winter','no','no','Hindu','ganapathi','ganapathi',10,'Banglore','india');
INSERT INTO festivamood VALUES(18,'ghatastapana','2022-01-15','tuesday','dasatra','india','holige','Both','ALL','May be',2,'winter','no','no','Hindu','devi','devi',10,'Banglore','india');
INSERT INTO festivamood VALUES(19,'Naraka Chaturthi','2022-01-15','wednesday','depavali','india','sweet','Both','ALL','May be',2,'winter','no','no','Hindu','ganapathi','ganapathi',10,'Banglore','india');
INSERT INTO festivamood VALUES(20,'ekadashi','2022-01-15','monday','pandarinath','KA','sweet','Both','ALL','May be',2,'winter','no','no','Hindu','hanuman','hanuman',10,'Banglore','india');
INSERT INTO festivamood VALUES(21,'tulasi maduve','2022-01-15','tuesday','maduve','KA','holige','Both','ALL','May be',2,'winter','no','no','Hindu','rama ','rama',10,'Banglore','india');
INSERT INTO festivamood VALUES(22,'rakhi hunneme','2022-01-15','wednesday','raksha bandhana','AP','holege','Both','ALL','May be',2,'winter','no','no','Hindu','krishana','krishana',10,'Banglore','india');
INSERT INTO festivamood VALUES(23,'devara pooje','2022-01-15','thersday','Ellu_bella','--','Vabbottu','Both','ALL','May be',2,'winter','no','no','Hindu','devi','devi',10,'Banglore','india');
INSERT INTO festivamood VALUES(24,'mane pooje','2022-01-15','friday','Ellu_bella','AP','holige','Both','ALL','May be',2,'winter','no','no','Hindu','lakshmi','lakshmi',10,'Banglore','india');
INSERT INTO festivamood VALUES(25,'panchami','2023-12-24','saturday','hola pooje','KA','bajji','Both','ALL','May be',2,'winter','yes','no','Hindu','----','----',10,'Banglore','india');
INSERT INTO festivamood VALUES(26,'Sankrati','2023-01-15','sunday','Ellu_bella','KA,AP,KL','Vabbottu','Both','ALL','May be',2,'winter','no','no','Hindu','Shabari male','Ayappa',10,'Banglore','india');
INSERT INTO festivamood VALUES(27,'Shivaratri','2023-02-12','monday','pooje','all over world','upavasa','Both','Shiva','no',1,'winter','yes','no','Hindu','Aurad','Amareshwar',15,'Banglore','india');
INSERT INTO festivamood VALUES(28,'Holi ','2023-03-04','tuesday','banna','KA,AP,MH','Holige','Both','Kamanna','No',1,'winter','no','no','Hindu','kalburgi','sharanabasappa',30,'Banglore','india');
INSERT INTO festivamood VALUES(29,'Ugadi','2023-03-22','Monday','hosavarusha for hindu','all over world','Holige ','Both','ALL','yes',1,'summmer','yes','no','Hindu','Kadaganchi','gramadevate',6,'Banglore','india');
INSERT INTO festivamood VALUES(30,'Sri Ram navami','2023-03-30','wednesday','ram birth','all over world','panaka','Both','ALL','yes',1,'summer','no','yes','Hindu','Ayoddhya','ram',100,'Banglore','india');
INSERT INTO festivamood VALUES(31,'Hanuman  jayanti','2023-04-06','wednesday','hanuma birth','all over world','panaka','Both','ALL','yes',1,'summer','yes','no','Hindu','hanuman palces','hanuma',10,'Banglore','india');
INSERT INTO festivamood VALUES(32,'Akshya tratiya','2023-04-22','saturday','basava jayanti','all over india','holige_mavin rasa','Both','ALL','yes',1,'summer','no','no','Hindu','basavakalyan','basavanna',10,'Banglore','india');
INSERT INTO festivamood VALUES(33,'Ramjan','2023-04-22','saturday','---','all over world','------','Both','ALL','yes',30,'summer','yes','yes','muslim','------','------',10,'Banglore','india');
INSERT INTO festivamood VALUES(34,'GURU-Purnime','2023-06-03','monday','Guru pooje','all over india','sweets','Both','ALL','May be',1,'rainy','no','yes','Hindu','-----','-----',10,'Banglore','india');
INSERT INTO festivamood VALUES(35,'moharam','2023-06-29','saturday','peer','KA','malodi','Both','ALL','yes',15,'rainy','',-'-','all','places ','--',10,'Banglore','india');
INSERT INTO festivamood VALUES(36,'shravan','2023-08-16','tuesday','prayer','KA,MH','sweets','Both','ALL','May be',30,'winter','no','no','Hindu','--- ','-----',10,'Banglore','india');
INSERT INTO festivamood VALUES(37,'ganesh charthi','2022-09-15','monday','ganapathi','india','holige','Both','ALL','May be',5,'rainy','no','no','Hindu','------','------',10,'Banglore','india');
INSERT INTO festivamood VALUES(38,'dasara','2022-01-15','saturday','devi','india','ckwvg','Both','ALL','May be',2,'winter','no','no','Hindu','devaru','shiva',10,'Banglore','india');
INSERT INTO festivamood VALUES(39,'dipavali','2022-01-15','tuesday','lakshmi','india','sdvhs','Both','ALL','May be',2,'winter','no','no','Hindu','shiva','devaru',10,'Banglore','india');
INSERT INTO festivamood VALUES(40,'srikrishna janmastami','2022-01-15','wednesday','krishana','KA','jfag','Both','ALL','May be',2,'winter','no','no','hindu','devi','devi',10,'Banglore','india');
INSERT INTO festivamood VALUES(41,'pooje','2022-01-15','sunday','gouri','india','chitranna','Both','ALL','May be',2,'winter','no','no','Hindu','lakshmi','lakshmi',10,'Banglore','india');
INSERT INTO festivamood VALUES(42,' pooje','2022-01-15','saturday','dasara','india','sweet','Both','ALL','May be',2,'winter','no','no','Hindu','ganapathi','ganapathi',10,'Banglore','india');
INSERT INTO festivamood VALUES(43,'deviii','2022-01-15','tuesday','dasatra','india','holige','Both','ALL','May be',2,'winter','no','no','Hindu','devi','devi',10,'Banglore','india');
INSERT INTO festivamood VALUES(44,'teachers day','2022-01-15','wednesday','depavali','india','sweet','Both','ALL','May be',2,'winter','no','no','Hindu','ganapathi','ganapathi',10,'Banglore','india');
INSERT INTO festivamood VALUES(45,'lalabhadru shatri jayanti','2022-01-15','monday','pandarinath','KA','sweet','Both','ALL','May be',2,'winter','no','no','Hindu','hanuman','hanuman',10,'Banglore','india');
INSERT INTO festivamood VALUES(46,'swami vivekanand jayanti','2022-01-15','tuesday','maduve','KA','holige','Both','ALL','May be',2,'winter','no','no','Hindu','rama ','rama',10,'Banglore','india');
INSERT INTO festivamood VALUES(47,'repepublic day','2022-01-15','wednesday','raksha bandhana','AP','holege','Both','ALL','May be',2,'winter','no','no','Hindu','krishana','krishana',10,'Banglore','india');
INSERT INTO festivamood VALUES(48,'childrens day','2022-01-15','thersday','Ellu_bella','--','Vabbottu','Both','ALL','May be',2,'winter','no','no','Hindu','devi','devi',10,'Banglore','india');
INSERT INTO festivamood VALUES(49,'independense day','2022-01-15','friday','Ellu_bella','AP','holige','Both','ALL','May be',2,'winter','no','no','Hindu','lakshmi','lakshmi',10,'Banglore','india');
INSERT INTO festivamood VALUES(50,'gandhijayanthi','2023-12-24','saturday','hola pooje','KA','bajji','Both','ALL','May be',2,'winter','yes','no','Hindu','----','----',10,'Banglore','india');


SELECT * FROM festivamood;
SELECT count(*) from festivamood;