use basicset;
Create table ksrtc(id int,bus_no int primary key,destination varchar(30));
INSERT INTO ksrtc values(1,645,'bidar');
INSERT INTO ksrtc values(2,810,'kukunoor');
INSERT INTO ksrtc values(3,715,'hb halli');
INSERT INTO ksrtc values(4,1272,'muddebihal');
INSERT INTO ksrtc values(5,1143,'hospete');
INSERT INTO ksrtc values(6,401,'belagam');
INSERT INTO ksrtc values(7,505,'hubbli');
INSERT INTO ksrtc values(8,666,'gadag');
INSERT INTO ksrtc values(9,2763,'bagalkota');
INSERT INTO ksrtc values(10,8088,'vijaypur');

create table driver(id int,name varchar(30),route_no int,foreign key(route_no) references ksrtc(bus_no));
INSERT INTO driver values(1,'Sangamesh',1272);
INSERT INTO driver values(2,'Iranna',715);
INSERT INTO driver values(3,'Bassu',810);
INSERT INTO driver values(4,'veeru',645);
INSERT INTO driver values(5,'santu',401);
INSERT INTO driver values(6,'shivu',666);
INSERT INTO driver values(7,'arun',505);
INSERT INTO driver values(8,'siddu',8088);
INSERT INTO driver values(9,'suryakant',2763);
INSERT INTO driver values(10,'pavan',1143);